Extract meta inf
CybercentreCanada/assemblyline-service-espresso pull request #2
Opened 2021-04-07 18:46 UTC by cccs-dawson

Changes to Espresso module:
	--a new results section is added to the report for manifest and certificate data
	--the main class and main package are included as tags in a subsection--see [AL common changes](https://github.com/CybercentreCanada/assemblyline-base/pull/169)
	--Use keytool to printcert. There is a subsection for each certificate. some meta info from the certificates(s) are included as tags. The entire certificate is dumped into the body.
	--some simple heuristics are also included based on the certificate metadata--the heuristics are similar to those used in APKaye

2021-04-07 22:47 UTC, cccs-sgaron requested changes

2021-04-07 22:47 UTC, cccs-sgaron commented on espresso.py
> +        #     print(f'---{name}: {type(path)}, {type(name)}, {type(desc)}')
Remove debug code

2021-04-07 22:47 UTC, cccs-sgaron commented on espresso.py
> +                        #         self.manifest_tags.append( ('file.jar.midlet.main_class', midlet_n[2]) )
Remove unused code

2021-04-07 22:47 UTC, cccs-sgaron commented on espresso.py
> +from assemblyline.common.keytool_parse import Certificate, certificate_chain_from_printcert, keytool_printcert
Keytool parse should be move to assemblyline_v4_service

2021-04-07 22:49 UTC, cccs-sgaron commented
We probably have to install keytool during the docker container creation, we are using a very minimal base image...

2021-05-17 18:41 UTC, cccs-rs commented
We'll want to move the keytool_parse module to be used locally instead of part of the service base:
https://github.com/CybercentreCanada/assemblyline-v4-service/pull/35

2021-05-18 11:57 UTC, merged